config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  devise_for :users, controllers: { registrations: "registrations" }

  resource :profile
  resources :movies, :actors

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_and_belongs_to_many :movies
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_and_belongs_to_many :actors

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  before_action :set_actor, only: [:show, :edit, :update, :destroy]

  def new
    @actor = Actor.new
  end

  def create
    @actor = Actor.new(actor_params)
    respond_to do |format|
      if @actor.save
        format.html { redirect_to @actor, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @actor }
      else
        format.html { render :new }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @actor.update_attributes(actor_params)
        format.html { redirect_to @actor, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @actor }
      else
        format.html { render :edit }
        format.json { render json: @actor.errors, status: :unprocessable_entity }
      end
    end
  end

  def show

  end

  def index
    @actors = Actor.all
  end

  def destroy
    @actor.destroy
    respond_to do |format|
      format.html { redirect_to actors_path, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def actor_params
    params.require(:actor).permit(:name, :year_of_birth, :thumbnail)
  end
  def set_actor
    @actor = Actor.find(params[:id])
    if !@actor
      redirect_to new_profile_path and return
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    profile_path
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @movie.update_attributes(movie_params)
        format.html { redirect_to @movie, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  def show

  end

  def index
    @movies = Movie.all
  end

  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_path, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def movie_params
    params.require(:movie).permit(:title, :summary, :embed_link, :thumbnail)
  end
  def set_movie
    @movie = Movie.find(params[:id])
    if !@movie
      redirect_to new_profile_path and return
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_profile, only: [:show, :edit, :update]
  before_action :authenticate_user!

  # GET /profiles/1
  # GET /profiles/1.json
  def show

  end

  # GET /profiles/new
  def new
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    if @movie.update_attributes(movie_params)
      redirect_to movie_path
    else
      render :edit
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = current_user.profile
      if !@profile
        redirect_to new_profile_path and return
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :user_id)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_inactive_sign_up_path_for(resource)
    edit_profile_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/actors/_form.html.erb
<%= form_for(@actor) do |f| %>
  <% if @actor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actor.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @actor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year_of_birth %><br>
    <%= f.text_field :year_of_birth %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<h1>Actors#edit</h1>


<%= render 'form' %>

<%= link_to 'Back', actors_path %>

app/views/actors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Actors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= actor.name %></td>
        <td><%= actor.thumbnail %></td>
        <td><%= link_to 'Show', actor_path(actor) %></td>
        <td><%= link_to 'Edit', edit_actor_path(actor) %></td>
        <td><%= link_to 'Destroy', actor_path(actor), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actor', new_actor_path %>

app/views/actors/new.html.erb
<h1>Actors#new</h1>

<%= render 'form' %>
|
<%= link_to 'Back', actors_path %>

app/views/actors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @actor.name %>
</p>

<p>
  <strong>year of birth:</strong>
  <%= @actor.year_of_birth %>
</p>
<p>
  <strong>thumbnail:</strong>
  <%= @actor.thumbnail %>
</p>


<%= link_to 'Back', actors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ImdbClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Img</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.thumbnail %></td>
        <td><%= link_to 'Show', movie_path(movie) %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie_path(movie), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>Movies#new</h1>
<p>Find me in app/views/movies/new.html.erb</p>

<%= render 'form' %>
|
<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @movie.summary %>
</p>
<p>
  <strong>YouTube:</strong>
  <%= @movie.embed_link %>
</p>
<p>
  <strong>Thumbnail:</strong>
  <%= @movie.thumbnail %>
</p>


<%= link_to 'Back', movies_path %>

app/views/profiles/_form.html.erb
<%= form_for(@profile, url: profile_path) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profile_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profile_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profile_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<% if user_signed_in? %>
  <div>Click <%= link_to 'here', destroy_user_session_path, method: :delete %> to sign out</div>

<% else %>
<div>Click <%= link_to 'here', new_user_registration_path %> to sign up</div>
<div>Click <%= link_to 'here', new_user_session_path %> to sign in</div>
<% end %>